@startuml
/'incoming call -- 显示notification start'/
Telecomm_Service -> InCallServiceImpl: bindService
InCallServiceImpl <-- InCallServiceImpl:onbind
Telecomm_Service <-- InCallServiceImpl: addListener()
Telecomm_Service --> InCallServiceImpl: onCallAdded
InCallServiceImpl --> InCallPresenter: onCallAdded

InCallPresenter --> CallList: onCallAdded
CallList --> DialerCall: new
DialerCall --> Telecomm_call: registerlistener
EnrichedCallManager --> DialerCall: registerCapabilitiesListener
EnrichedCallManager --> DialerCall: registerStateChangedListener
CallList --> DialerCall: setSpam
CallList --> DialerCall: setBlockedStatus

CallList --> CallList: onIncoming
CallList --> CallList: updateCallInMap
CallList --> InCallPresenter: onIncomingCall
InCallPresenter --> InCallPresenter: startOrFinishUi
InCallPresenter --> StatusBarNotifier: updateNotification

StatusBarNotifier --> StatusBarNotifier: showNotification
StatusBarNotifier --> ContactInfoCache:findInfo
ContactInfoCache --> StatusBarNotifier: onContactInfoComplete
StatusBarNotifier --> StatusBarNotifier: buildAndSendNotification
StatusBarNotifier --> StatusBarNotifier: configureFullScreenIntent
/'incoming call -- 显示notification end'/

/'incoming call -- 应答 start'/
StatusBarNotifier --> NotificationBroadcastReceiver: answerIncomingCall
NotificationBroadcastReceiver --> DialerCall: answer
DialerCall --> Telecomm_call: answer
Telecomm_call --> Telecomm_Service: answerCall
Telecomm_Service --> Telecomm_call: onStateChanged
DialerCall --> DialerCall: update
DialerCall --> CallList: onUpdateCall
CallList --> CallList: notifyGenericListeners
CallList --> InCallPresenter: onCallListChange
InCallPresenter --> InCallPresenter: startOrFinishUi
InCallPresenter --> InCallPresenter: showInCall
/'incoming call -- 应答 end'/
@enduml

@startuml
/'show activity start'/
IncallActivity --> IncallActivity: oncreate
IncallActivity --> IncallActivity: showMainInCallFragment
IncallActivity --> InCallFragment: showInCallScreenFragment
InCallFragment --> InCallFragment: oncreate
InCallFragment --> CallButtonPresenter: new
InCallFragment --> InCallFragment: onCreateView
InCallFragment --> LockableViewPager: new
InCallFragment --> ContactGridManager: onViewCreated
InCallFragment --> CallCardPresenter: new
CallCardPresenter --> CallCardPresenter: onInCallScreenDelegateInit
CallCardPresenter --> DialerCall: addListener
CallCardPresenter --> ContactInfoCache: findInfo
CallCardPresenter --> CallCardPresenter: onInCallScreenReady
CallCardPresenter --> CallCardPresenter: updatePrimaryDisplayInfo
CallCardPresenter --> InCallPresenter: registerListener
CallCardPresenter --> InCallFragment: setPrimary
InCallFragment --> InCallFragment: setAdapterMedia
InCallFragment --> MultimediaFragment: newInstance
InCallFragment --> InCallButtonGridFragment: newInstance
InCallFragment --> ContactGridManager: setPrimary

/'show activity end'/
@enduml